# Site settings
title: DAC Blog                    # 你的博客网站标题
SEOTitle: 戴傲初的博客 | DAC Blog		# SEO 标题
description: "Hey"	   	   # 随便说点，描述一下

# SNS settings      
github_username: Acdimy     # 你的github账号

# Build settings
# paginate: 10              # 一页你准备放几篇文章