# Site settings
title: DAC Blog                    # 你的博客网站标题
SEOTitle: 傲初的博客 | DAC Blog		# SEO 标题
description: "Attendre et espérer"	   	   # 随便说点，描述一下
header-img: img/post-bg-desk.jpg
email: lydac9000@gmail.com
url: "http://Acdimy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Acdimy/Acdimy.github.io.git"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "青年学生与哲学爱好者"
sidebar-avatar: /img/about-DAC-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings      
github_username: Acdimy     # 你的github账号

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true